#!/usr/bin/env python3
"""Build the static GitHub Pages demo of the IPS Command UI.

Outputs into <repo>/docs/demo/:
  index.html                  — copy of tools/templates/index.html with
                                absolute /assets/ paths rewritten and
                                <script>window.IPS_DEMO=true;</script>
                                injected so the in-page demo shim takes
                                over /api/* fetches.
  assets/                     — copy of mascot GIFs and Octocat mark.
  data/sessions/index.json    — session list (matches /api/sessions).
  data/sessions/<id>.json     — individual session payloads.

Re-run any time tools/templates/index.html changes:
  python3 tools/build_demo.py
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import random
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_HTML = ROOT / "tools" / "templates" / "index.html"
SRC_ASSETS = ROOT / "tools" / "templates" / "assets"
OUT = ROOT / "docs" / "demo"
OUT_ASSETS = OUT / "assets"
OUT_DATA = OUT / "data" / "sessions"

# Optional local config (gitignored) supplies LIVE_PASSWORD + LIVE_DEFAULT_URL
_LIVE_PW = ""
_LIVE_DEFAULT_URL = ""
try:
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    from local_config import (  # type: ignore
        LIVE_PASSWORD as _LIVE_PW,
        LIVE_DEFAULT_URL as _LIVE_DEFAULT_URL,
    )
except Exception:
    pass

# env vars override local_config
_LIVE_PW = os.environ.get("LIVE_PASSWORD", _LIVE_PW)
_LIVE_DEFAULT_URL = os.environ.get("LIVE_DEFAULT_URL", _LIVE_DEFAULT_URL)

LIVE_HASH = hashlib.sha256(_LIVE_PW.encode("utf-8")).hexdigest() if _LIVE_PW else ""

DEMO_BANNER = (
    "<!-- AUTO-GENERATED by tools/build_demo.py — do not edit by hand. "
    "Edit tools/templates/index.html and rerun the script. -->\n"
)
# Demo flag + LIVE-mode hash injection.  The hash is sha-256(password);
# the password itself is NEVER written to disk under docs/.  Visitors
# who don't know the password cannot derive it from this file.
DEMO_FLAG = (
    "<script>\n"
    "  window.IPS_DEMO = true;\n"
    f"  window.IPS_LIVE_HASH = {json.dumps(LIVE_HASH)};\n"
    f"  window.IPS_LIVE_DEFAULT_URL = {json.dumps(_LIVE_DEFAULT_URL)};\n"
    "</script>\n"
)


def build_html() -> None:
    src = SRC_HTML.read_text(encoding="utf-8")
    # Rewrite absolute /assets/ paths to relative so GH Pages subpaths work.
    out = src.replace('"/assets/', '"assets/').replace("='/assets/", "='assets/")
    # Inject the demo flag immediately before the first <script>.
    out = out.replace("<script>", DEMO_FLAG + "<script>", 1)
    out = DEMO_BANNER + out
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "index.html").write_text(out, encoding="utf-8")
    print(f"  wrote {OUT/'index.html'}  ({len(out):,} bytes)")


def copy_assets() -> None:
    OUT_ASSETS.mkdir(parents=True, exist_ok=True)
    for p in SRC_ASSETS.iterdir():
        if p.is_file():
            shutil.copy2(p, OUT_ASSETS / p.name)
            print(f"  copied {p.name}  ({p.stat().st_size/1024:.1f} KB)")


def synth_session(name: str, seed: int, kp: float, kd: float, pneg: float,
                  bias: float, fall_after_ms: int | None) -> dict:
    """Generate a plausible-looking session for demo display.

    fall_after_ms = None  → stable run (standing)
    fall_after_ms = int    → simulated fall in that direction's bias.
    """
    rng = random.Random(seed)
    samples: list[dict] = []
    t = 0
    angle = rng.uniform(-2, 2)
    dangle = 0.0
    # Closed-loop sim with "true" controller, then optional perturbation.
    DT = 50  # ms between samples
    duration = fall_after_ms + 800 if fall_after_ms else 16000
    falling = False
    fall_dir = 1 if rng.random() < 0.5 else -1
    while t < duration:
        # simple inverted-pendulum dynamics
        accel = 0.18 * angle  # gravity-like (positive feedback)
        # controller
        ctrl = -(kp * angle + kd * dangle)
        if angle < 0:
            ctrl *= pneg
        ctrl += bias * 5
        ctrl = max(-350, min(350, ctrl))
        accel += -0.012 * ctrl  # motor effect
        accel += rng.gauss(0, 0.05)  # noise
        if falling:
            accel += fall_dir * 0.6  # runaway
        dangle += accel
        dangle *= 0.985  # damping
        angle += dangle * (DT / 1000.0)
        if fall_after_ms is not None and t >= fall_after_ms and not falling:
            falling = True
        if abs(angle) > 35:
            angle = max(-45, min(45, angle))
            dangle *= 0.4
        samples.append({
            "t": t,
            "angle": round(angle, 2),
            "dangle": round(dangle, 2),
            "power": int(ctrl),
            "p": round(kp * angle, 2),
            "d": round(kd * dangle, 2),
            "speed": round(dangle * 0.05, 3),
        })
        t += DT
    # stats (mirrors computeStats in index.html)
    max_abs = 0.0
    sum_abs = 0.0
    green = 0
    zc = 0
    prev_sign = 0
    for s in samples:
        ab = abs(s["angle"])
        if ab > max_abs:
            max_abs = ab
        sum_abs += ab
        if ab <= 5:
            green += 1
        sign = 1 if s["angle"] > 1 else -1 if s["angle"] < -1 else 0
        if sign and prev_sign and sign != prev_sign:
            zc += 1
        if sign:
            prev_sign = sign
    last = samples[-1]["angle"]
    fall_d = "standing" if abs(last) <= 20 else ("backward" if last > 0 else "forward")
    dur_s = samples[-1]["t"] / 1000.0
    green_ratio = green / len(samples)
    mean_abs = sum_abs / len(samples)
    score = round(min(30, dur_s * 3) + green_ratio * 50 + max(0, 20 - mean_abs * 2))
    return {
        "name": name,
        "ts": 1745000000000 + seed * 1000,
        "duration": samples[-1]["t"],
        "params": {
            "kp": kp, "kd": kd, "ki": 3.2, "kspd": 0.08,
            "ppos": 1.0, "pneg": pneg, "bias": bias,
            "alim": 45, "plim": 350, "kpower": 0.0001, "minp": 0, "po": 0,
        },
        "samples": samples,
        "stats": {
            "max_abs_angle": round(max_abs, 2),
            "max_angle": round(max((s["angle"] for s in samples), key=abs), 2),
            "fall_dir": fall_d,
            "zero_cross": zc,
            "osc_hz": round(zc / 2 / dur_s, 2) if dur_s else 0,
            "green_ratio": round(green_ratio, 3),
            "mean_abs_angle": round(mean_abs, 2),
            "score": score,
        },
    }


SESSIONS = [
    # (id, name, seed, kp, kd, pneg, bias, fall_after_ms)
    ("20250419_120000_baseline",     "baseline",      1, 35, 5.0, 1.0, -0.5,  900),
    ("20250419_121500_kp_too_high",  "kp_too_high",   2, 80, 4.0, 1.0,  0.0, 1400),
    ("20250419_123000_better_kd",    "better_kd",     3, 45, 9.0, 1.1, -0.3, 6500),
    ("20250419_124500_pneg_tuned",   "pneg_tuned",    4, 50, 9.5, 1.3, -0.4, None),
    ("20250419_130000_winner",       "winner",        5, 55, 10.5, 1.25, -0.4, None),
]


def build_sessions() -> None:
    OUT_DATA.mkdir(parents=True, exist_ok=True)
    index = []
    for sid, name, seed, kp, kd, pneg, bias, fall in SESSIONS:
        d = synth_session(name, seed, kp, kd, pneg, bias, fall)
        (OUT_DATA / f"{sid}.json").write_text(json.dumps(d, indent=1), encoding="utf-8")
        index.append({
            "id": sid,
            "name": d["name"],
            "ts": d["ts"],
            "duration": d["duration"],
            "samples": len(d["samples"]),
            "max_abs_angle": d["stats"]["max_abs_angle"],
            "fall_dir": d["stats"]["fall_dir"],
            "green_ratio": d["stats"]["green_ratio"],
            "mean_abs_angle": d["stats"]["mean_abs_angle"],
            "score": d["stats"]["score"],
            "params": d["params"],
        })
        print(f"  built {sid}.json  score={d['stats']['score']:>3}  fall={d['stats']['fall_dir']}")
    (OUT_DATA / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8")
    print(f"  wrote index.json  ({len(index)} sessions)")


def main() -> None:
    print(f"building demo into {OUT}")
    if LIVE_HASH:
        print(f"  LIVE gate    : enabled (sha256={LIVE_HASH[:12]}…)")
    else:
        print(f"  LIVE gate    : disabled (no LIVE_PASSWORD set)")
    build_html()
    copy_assets()
    build_sessions()
    print("done.")


if __name__ == "__main__":
    main()
